project:
  type: website

website:
  title: "Teresa Sha"
navbar:
  left:
  - text: "Home"
href: index.qmd
- text: "Resume"
href: resume.qmd
right:
  - icon: github
href: https://github.com/Teresa698
- icon: envelope
href: mailto:qs2301@cumc.columbia.edu

format:
  html:
  theme: cosmo
toc: true

